import type { UdpConfig } from ".";

export const udpConfig: UdpConfig = {
  "Dock Messages": {
    Prefixes: {
      "7": {
        prefix_description: "Pin ID",
        Description: "Pin Measure",
        Fields: [
          {
            label: "eDiagInfo",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "STAT_INACTIVE",
              "1": "STAT_DONE",
              "2": "STAT_BUSY",
              "3": "STAT_PREPARING",
              "4": "STAT_READY",
              "5": "STAT_RESET",
              "6": "STAT_ABORTED",
              "7": "RESERVED_07",
              "8": "RESERVED_08",
              "9": "RESERVED_09",
              "10": "ERR_OPEN_CIRCUIT",
              "11": "ERR_SHORT_CIRCUIT",
              "12": "ERR_OVERLOAD_CURRENT",
              "13": "ERR_LOW_CURRENT",
              "14": "ERR_UNDERVOLTAGE_VBBX",
              "15": "ERR_OVERVOLTAGE_VBBX",
              "16": "ERR_STUCK_AT_HIGH",
              "17": "ERR_STUCK_AT_LOW",
              "18": "ERR_HIGH_TEMPERATURE",
              "19": "ERR_LOW_TEMPERATURE",
              "20": "ERR_INVALID_VALUE",
              "21": "ERR_INVALID_CHANNEL",
              "22": "ERR_INVALID_MODE",
              "23": "ERR_INVALID_FREQUENCY",
              "24": "ERR_INVALID_DITHER",
              "25": "ERR_INVALID_FILTER",
              "26": "ERR_UNREACHABLE_CURRENT",
              "27": "ERR_SLOW_SIGNAL",
              "28": "ERR_CHANGEOVER_TIME",
              "29": "ERR_INSTANCE",
              "30": "ERR_INSTANCE_LIMIT",
              "31": "ERR_INVALID_COLOUR",
              "32": "ERR_NO_IDENTITY",
              "33": "ERR_ACCESS",
              "34": "ERR_UNDEFINED",
              "35": "ERR_FUNC_KEY_MISSED",
              "36": "ERR_BUFFER_OVERFLOW",
              "37": "ERR_BAUDRATE_ALREADY_SET",
              "38": "ERR_INACTIVE_INTERFACE",
              "39": "ERR_TIMEOUT",
              "40": "ERR_OUT_OF_MEMORY",
              "41": "ERR_BUS_OFF",
              "42": "ERR_BAD_CRC",
              "43": "ERR_EXCEEDED_RANGE",
              "44": "ERR_INTERNAL_COMMUNICATION",
              "45": "ERR_NOT_SUPPORTED",
              "46": "ERR_TIMING",
              "47": "ERR_INTERNAL",
              "48": "ERR_FILE_SYSTEM",
              "49": "ERR_INVALID_IP_CFG",
              "50": "ERR_FAILED_ERR_RESET",
              "51": "ERR_DEVICE_NOT_AVAILABLE",
              "52": "ERR_NO_OBJECT",
              "53": "ERR_UNREACHABLE_VOLTAGE",
              "54": "ERR_AT_GROUP_OUTPUT",
              "55": "ERR_CONTROL_DITHER",
              "56": "ERR_UNDERVOLTAGE_VBBX_WARNING",
              "57": "ERR_OVERVOLTAGE_VBBX_WARNING",
              "58": "ERR_LOW_TEMPERATURE_WARNING",
              "59": "ERR_HIGH_TEMPERATURE_WARNING",
              "60": "ERR_RANGE_OVERRUN",
              "61": "ERR_RANGE_UNDERRUN",
              "62": "DIAG_INVALID_VALUE",
              "63": "DIAG_INTERNAL",
              "64": "DIAG_OPEN_CIRCUIT",
              "65": "DIAG_SHORT_CIRCUIT",
              "66": "DIAG_UNDERVOLTAGE_VBBX",
              "67": "DIAG_OVERVOLTAGE_VBBX",
              "68": "DIAG_OVERLOAD_CURRENT",
              "69": "DIAG_STUCK_AT",
              "70": "DIAG_STUCK_AT_HIGH",
              "71": "DIAG_STUCK_AT_LOW",
              "72": "DIAG_INVALID_COLOUR",
              "73": "DIAG_OVERVOLTAGE",
              "74": "DIAG_UNDERVOLTAGE",
              "75": "DIAG_NO_CALIB",
              "76": "DIAG_ACCESS",
              "77": "DIAG_CHANGEOVER_TIME",
              "78": "ERR_OVERVOLTAGE",
              "79": "ERR_UNDERVOLTAGE",
              "80": "ERR_STUCK_AT",
              "81": "DIAG_CONTROL_DITHER",
              "82": "DIAG_SLOW_SIGNAL",
              "83": "DIAG_DIAG_PRO_MODE",
              "84": "DIAG_WINDOW",
              "85": "ERR_SDO_IDX_NOT_EXIST",
              "86": "ERR_SDO_SUBIDX_NOT_EXIST",
              "87": "ERR_SDO_UNSUPPORTED_ACCESS",
              "88": "ERR_SDO_DATA_TYPE",
              "89": "DIAG_LOW_TEMPERATURE",
              "90": "DIAG_HIGH_TEMPERATURE",
              "91": "DIAG_INVALID_DITHER",
              "92": "DIAG_INVALID_FREQUENCY",
              "93": "DIAG_RANGE_OVERRUN",
              "94": "DIAG_RANGE_UNDERRUN",
              "95": "DIAG_INVALID_FILTER",
              "96": "ERR_COMPARE_MISMATCH",
              "97": "DIAG_INVALID_IP_CFG",
              "98": "DIAG_LOW_CURRENT",
              "99": "DIAG_AT_GROUP_OUTPUT",
              "100": "ERR_SDO_UNKNOWN",
              "101": "ERR_BAUDRATE_INVALID_OR_ALREADY_SET",
              "102": "DIAG_COMPARE_MISMATCH",
              "103": "DIAG_COMPARE_MISMATCH_VSYS",
              "104": "DIAG_GROUP_OVERLOAD_CURRENT",
              "105": "ERR_GROUP_OVERLOAD_CURRENT",
              "106": "STAT_PAUSED",
              "107": "STAT_ABORT",
              "108": "STAT_EVNT_OPEN_PLUG_STORAGE",
              "109": "STAT_EVNT_OPEN_UNPLUG_STORAGE",
              "110": "STAT_EVNT_OPEN_DONE",
              "111": "STAT_EVNT_REGI_PLUG_STORAGE",
              "112": "STAT_EVNT_REGI_UNPLUG_STORAGE",
              "113": "STAT_EVNT_REGI_DONE",
              "114": "STAT_EVNT_UNREGI",
              "115": "STAT_EVNT_UNREGI_DONE",
              "116": "STAT_EVNT_CLOSE",
              "117": "STAT_EVNT_CLOSE_DONE",
              "118": "ERR_INSTANCE_RESTRICTION",
              "119": "ERR_NO_FILE",
              "120": "ERR_EVNT_OPEN",
              "121": "ERR_EVNT_REGI",
              "122": "ERR_EVNT_UNREGI",
              "123": "ERR_EVNT_CLOSE",
              "124": "ERR_GET_STORAGE_LIST",
              "125": "ERR_UNPLUG_STORAGE",
              "126": "DIAG_INVALID_CHANNEL",
              "127": "DIAG_INVALID_MODE",
              "128": "ERR_H_BRIDGE_TEST",
              "129": "ERR_GROUP_SW_TEST",
              "130": "ERR_TX_ERROR",
              "131": "ERR_RX_ERROR",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [0],
          },
          {
            label: "eMode",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "ERROR",
              "1": "BH_o",
              "2": "PWM_H_o",
              "3": "PWM_I_o",
              "4": "BL_o",
              "5": "PWM_L_o",
              "6": "R_i",
              "7": "BL_i",
              "8": "Av32_i",
              "9": "FREQ_L_i",
              "10": "BH_i",
              "11": "Ai_i",
              "12": "Av10_i",
              "13": "FREQ_H_i",
              "14": "OFF",
              "15": "VIRTUAL",
              "16": "RELAY",
              "17": "HBridge_o",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [1],
          },
          {
            label: "OutState",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "Error",
              "1": "Good",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [2],
          },
          {
            label: "IO_ID",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 1,
            unit: "",
            bits: [
              {
                Name: "ID",
                Start: 0,
                Num: 7,
              },
              {
                Name: "IsInput",
                Start: 7,
                Num: 1,
              },
            ],
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [3],
          },
          {
            dependent_on: {
              byte: 19,
              bit: 7,
            },
            label: "Decoded | Voltage",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: " | mV",
            multiplier: 1.0,
            type: "uint16_t",
            bytes: [4, 5],
          },
          {
            dependent_on: {
              byte: 19,
              bit: 7,
            },
            label: "Raw | Current",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: " | uA",
            multiplier: 1.0,
            type: "uint16_t",
            bytes: [6, 7],
          },
        ],
      },
      "16": {
        prefix_description: "Valve",
        Description: "Payload Fill Status[es]",
        Fields: [
          {
            label: "Fill Type",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "Disabled",
              "1": "Water",
              "2": "LiquidChemical",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [0],
          },
          {
            label: "Delivered",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "No",
              "1": "Yes",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [1],
          },
          {
            label: "InjectionState",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "Disabled",
              "1": "Waiting",
              "2": "Injecting",
              "3": "Flushing",
              "4": "Finished",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [2],
          },
          {
            label: "Delivery Order",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [3],
          },
          {
            label: "Transfer Rate Measured",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "L/s",
            multiplier: 1.0,
            type: "float",
            bytes: [4, 5, 6, 7],
          },
          {
            label: "Chem Volume Measured",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "L",
            multiplier: 1.0,
            type: "float",
            bytes: [8, 9, 10, 11],
          },
          {
            label: "Water before Injection Measured",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "L",
            multiplier: 1.0,
            type: "float",
            bytes: [12, 13, 14, 15],
          },
          {
            label: "Volume Requested Response",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "L",
            multiplier: 1.0,
            type: "float",
            bytes: [16, 17, 18, 19],
          },
          {
            label: "Flush Volume Measured",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "L",
            multiplier: 1.0,
            type: "float",
            bytes: [20, 21, 22, 23],
          },
          {
            label: "Volume Remaining",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "L",
            multiplier: 1.0,
            type: "float",
            bytes: [24, 25, 26, 27],
          },
        ],
      },
    },
    Messages: {
      "1": {
        Description: "Dock Connection Status",
        Fields: [
          {
            label: "Ready To Dock",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "No",
              "1": "Yes",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [0],
          },
          {
            label: "Ready To Fill",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "No",
              "1": "Yes",
              "2": "Resuming",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [1],
          },
          {
            label: "Fill Finished",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "No",
              "1": "Yes",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [2],
          },
          {
            label: "Reserved",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [3],
          },
          {
            label: "SwarmBot ID Accepted For Refill",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint16_t",
            bytes: [4, 5],
          },
          {
            label: "Reserved",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [6],
          },
          {
            label: "Reserved",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [7],
          },
        ],
      },
      "2": {
        Description: "Dock Info",
        Fields: [
          {
            label: "Fuel Level",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "%",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [0],
          },
          {
            label: "Tank Level",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "%",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [1],
          },
          {
            label: "Tank Volume",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "L",
            multiplier: 1.0,
            type: "uint16_t",
            bytes: [2, 3],
          },
          {
            label: "Engine Speed",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "RPM",
            multiplier: 1.0,
            type: "uint16_t",
            bytes: [4, 5],
          },
          {
            label: "Reserved",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [6],
          },
          {
            label: "Reserved",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [7],
          },
          {
            label: "Battery Voltage",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "V",
            multiplier: 1.0,
            type: "float",
            bytes: [8, 9, 10, 11],
          },
          {
            label: "Major Version Number",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [12],
          },
          {
            label: "Minor Version Number",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [13],
          },
          {
            label: "Patch Version Number",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [14],
          },
          {
            label: "Reserved",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [15],
          },
        ],
      },
      "3": {
        Description: "Water Fill Status",
        Fields: [
          {
            label: "Transfer Rate Measured",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "L/s",
            multiplier: 1.0,
            type: "float",
            bytes: [0, 1, 2, 3],
          },
          {
            label: "Pump Pressure",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "Bar",
            multiplier: 1.0,
            type: "float",
            bytes: [4, 5, 6, 7],
          },
          {
            label: "Volume Delivered",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "L",
            multiplier: 1.0,
            type: "float",
            bytes: [8, 9, 10, 11],
          },
        ],
      },
      "4": {
        Description: "Dock Errors",
        Fields: [
          {
            label: "Error Category",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [0],
          },
          {
            label: "Active",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "Active",
              "255": "Inactive",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [1],
          },
          {
            label: "Error Code",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint16_t",
            bytes: [2, 3],
          },
          {
            label: "Reserved",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [4],
          },
          {
            label: "Reserved",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [5],
          },
          {
            label: "Reserved",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [6],
          },
          {
            label: "Reserved",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [7],
          },
          {
            label: "Payload",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint64_t",
            bytes: [8, 9, 10, 11, 12, 13, 14, 15],
          },
        ],
      },
      "6": {
        Description: "Calibration Param",
        Fields: [
          {
            label: "ID Resp",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint16_t",
            bytes: [0, 1],
          },
          {
            label: "Resp",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "255": "WriteSuccess",
              "240": "ReadSuccess",
              "15": "Fail",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [2],
          },
          {
            label: "Var Type",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "BOOL",
              "1": "BYTE",
              "2": "WORD",
              "3": "DWORD",
              "4": "LWORD",
              "5": "SINT",
              "6": "INT",
              "7": "DINT",
              "8": "LINT",
              "9": "REAL",
              "10": "LREAL",
              "11": "TIME",
            },
            multiplier: 1.0,
            type: null,
            bytes: [3],
          },
          {
            label: "Index1",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [4],
          },
          {
            label: "Index2",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [5],
          },
          {
            label: "Value Resp",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint64_t",
            bytes: [6, 7, 8, 9, 10, 11, 12, 13],
          },
        ],
      },
      "7": {
        Description: "Current Hash",
        Fields: [
          {
            label: "Hash",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint64_t",
            bytes: [0, 1, 2, 3, 4, 5, 6, 7],
          },
        ],
      },
      "8": {
        Description: "Multi Param Response",
        Fields: [
          {
            label: "ID Resp",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint16_t",
            bytes: [0, 1],
          },
          {
            label: "Resp",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "255": "WriteSuccess",
              "240": "ReadSuccess",
              "15": "Fail",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [2],
          },
          {
            label: "Var Type",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "BOOL",
              "1": "BYTE",
              "2": "WORD",
              "3": "DWORD",
              "4": "LWORD",
              "5": "SINT",
              "6": "INT",
              "7": "DINT",
              "8": "LINT",
              "9": "REAL",
              "10": "LREAL",
              "11": "TIME",
            },
            multiplier: 1.0,
            type: null,
            bytes: [3],
          },
          {
            label: "Index1",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [4],
          },
          {
            label: "Index2",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [5],
          },
          {
            label: "Value Resp",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint64_t",
            bytes: [6, 7, 8, 9, 10, 11, 12, 13],
          },
        ],
      },
      "9": {
        Description: "Array Param Response",
        Fields: [
          {
            label: "ID Resp",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint16_t",
            bytes: [0, 1],
          },
          {
            label: "Resp",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "255": "WriteSuccess",
              "240": "ReadSuccess",
              "15": "Fail",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [2],
          },
          {
            label: "Var Type",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "BOOL",
              "1": "BYTE",
              "2": "WORD",
              "3": "DWORD",
              "4": "LWORD",
              "5": "SINT",
              "6": "INT",
              "7": "DINT",
              "8": "LINT",
              "9": "REAL",
              "10": "LREAL",
              "11": "TIME",
            },
            multiplier: 1.0,
            type: null,
            bytes: [3],
          },
          {
            label: "Index1 Start",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [4],
          },
          {
            label: "Index1 End",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [5],
          },
          {
            label: "Index2 Start",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [6],
          },
          {
            label: "Index2 End",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [7],
          },
          {
            label: "Value Resp",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint64_t",
            bytes: [8, 9, 10, 11, 12, 13, 14, 15],
          },
        ],
      },
      "10": {
        Description: "Last Fill Info",
        Fields: [
          {
            label: "Last Accepted ID",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint16_t",
            bytes: [0, 1],
          },
          {
            label: "Last Refill ID",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint16_t",
            bytes: [2, 3],
          },
          {
            label: "Water Requested",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [4, 5, 6, 7],
          },
          {
            label: "Water Delivered",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [8, 9, 10, 11],
          },
          {
            label: "Product 1 Requested L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [12, 13, 14, 15],
          },
          {
            label: "Product 2 Requested L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [16, 17, 18, 19],
          },
          {
            label: "Product 3 Requested L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [20, 21, 22, 23],
          },
          {
            label: "Product 4 Requested L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [24, 25, 26, 27],
          },
          {
            label: "Product 5 Requested L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [28, 29, 30, 31],
          },
          {
            label: "Product 6 Requested L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [32, 33, 34, 35],
          },
          {
            label: "Product 7 Requested L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [36, 37, 38, 39],
          },
          {
            label: "Fill 1 Type",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "Disabled",
              "1": "Water",
              "2": "LiquidChemical",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [40],
          },
          {
            label: "Fill 2 Type",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "Disabled",
              "1": "Water",
              "2": "LiquidChemical",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [41],
          },
          {
            label: "Fill 3 Type",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "Disabled",
              "1": "Water",
              "2": "LiquidChemical",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [42],
          },
          {
            label: "Fill 4 Type",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "Disabled",
              "1": "Water",
              "2": "LiquidChemical",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [43],
          },
          {
            label: "Fill 5 Type",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "Disabled",
              "1": "Water",
              "2": "LiquidChemical",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [44],
          },
          {
            label: "Fill 6 Type",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "Disabled",
              "1": "Water",
              "2": "LiquidChemical",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [45],
          },
          {
            label: "Fill 7 Type",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "Disabled",
              "1": "Water",
              "2": "LiquidChemical",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [46],
          },
          {
            label: "Reserved",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [47],
          },
          {
            label: "Product 1 Delivered L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [48, 49, 50, 51],
          },
          {
            label: "Product 2 Delivered L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [52, 53, 54, 55],
          },
          {
            label: "Product 3 Delivered L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [56, 57, 58, 59],
          },
          {
            label: "Product 4 Delivered L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [60, 61, 62, 63],
          },
          {
            label: "Product 5 Delivered L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [64, 65, 66, 67],
          },
          {
            label: "Product 6 Delivered L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [68, 69, 70, 71],
          },
          {
            label: "Product 7 Delivered L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [72, 73, 74, 75],
          },
          {
            label: "Flush 1 Delivered L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [76, 77, 78, 79],
          },
          {
            label: "Flush 2 Delivered L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [80, 81, 82, 83],
          },
          {
            label: "Flush 3 Delivered L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [84, 85, 86, 87],
          },
          {
            label: "Flush 4 Delivered L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [88, 89, 90, 91],
          },
          {
            label: "Flush 5 Delivered L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [92, 93, 94, 95],
          },
          {
            label: "Flush 6 Delivered L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [96, 97, 98, 99],
          },
          {
            label: "Flush 7 Delivered L",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "float",
            bytes: [100, 101, 102, 103],
          },
        ],
      },
    },
  },
  "SwarmBot Messages": {
    Prefixes: {
      "16": {
        prefix_description: "Product",
        Description: "Payload Fill Request[s]",
        Fields: [
          {
            label: "Fill Type",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "Disabled",
              "1": "Water",
              "2": "LiquidChemical",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [0],
          },
          {
            label: "Delivery Order",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [1],
          },
          {
            label: "Reserved",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [2],
          },
          {
            label: "Reserved",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [3],
          },
          {
            label: "Volume Requested",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "L",
            multiplier: 1.0,
            type: "float",
            bytes: [4, 5, 6, 7],
          },
          {
            label: "Water before Injection Requested",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "L",
            multiplier: 1.0,
            type: "float",
            bytes: [8, 9, 10, 11],
          },
          {
            label: "Available Valves",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint16_t",
            bytes: [12, 13],
          },
          {
            label: "Reserved",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [14],
          },
          {
            label: "Reserved",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [15],
          },
        ],
      },
      "17": {
        prefix_description: "Tank",
        Description: "Tank Level[s]",
        Fields: [
          {
            label: "Reset Tank",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "No",
              "254": "Yes",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [0],
          },
          {
            label: "Actual Tank Level",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "L",
            multiplier: 1.0,
            type: "float",
            bytes: [1],
          },
          {
            label: "Reserved",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [2],
          },
          {
            label: "Reserved",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [3],
          },
          {
            label: "Actual Tank Level",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "L",
            multiplier: 1.0,
            type: "float",
            bytes: [4, 5, 6, 7],
          },
        ],
      },
    },
    Messages: {
      "1": {
        Description: "Swarmbot Connection Status",
        Fields: [
          {
            label: "Refill Request",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "NoRefill",
              "1": "NewRefill",
              "2": "ResumeRefill",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [0],
          },
          {
            label: "Ready To Fill",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "No",
              "1": "Yes",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [1],
          },
          {
            label: "Refill ID",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint16_t",
            bytes: [2, 3],
          },
        ],
      },
      "2": {
        Description: "Water Fill Request",
        Fields: [
          {
            label: "Volume Requested",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "L",
            multiplier: 1.0,
            type: "float",
            bytes: [0, 1, 2, 3],
          },
          {
            label: "Transfer Rate Requested",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "L/s",
            multiplier: 1.0,
            type: "float",
            bytes: [4, 5, 6, 7],
          },
          {
            label: "Transfer Rate Requested For When Injecting",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "L/s",
            multiplier: 1.0,
            type: "float",
            bytes: [8, 9, 10, 11],
          },
        ],
      },
      "3": {
        Description: "Calibration Param",
        Fields: [
          {
            label: "ID Req",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint16_t",
            bytes: [0, 1],
          },
          {
            label: "Req",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "Read",
              "255": "Write",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [2],
          },
          {
            label: "Var Type",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "BOOL",
              "1": "BYTE",
              "2": "WORD",
              "3": "DWORD",
              "4": "LWORD",
              "5": "SINT",
              "6": "INT",
              "7": "DINT",
              "8": "LINT",
              "9": "REAL",
              "10": "LREAL",
              "11": "TIME",
            },
            multiplier: 1.0,
            type: null,
            bytes: [3],
          },
          {
            label: "Index1",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [4],
          },
          {
            label: "Index2",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [5],
          },
          {
            label: "Value",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint64_t",
            bytes: [6, 7, 8, 9, 10, 11, 12, 13],
          },
        ],
      },
      "4": {
        Description: "Debug",
        Fields: [
          {
            label: "Actual Volume Received into Tank on SwarmBot",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "L",
            multiplier: 1.0,
            type: "float",
            bytes: [0, 1, 2, 3],
          },
        ],
      },
      "5": {
        Description: "Reset Error",
        Fields: [
          {
            label: "Error Category",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [0],
          },
          {
            label: "Reset Error",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "No",
              "254": "Yes",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [1],
          },
          {
            label: "Error Code",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint16_t",
            bytes: [2, 3],
          },
        ],
      },
      "6": {
        Description: "Set Hash",
        Fields: [
          {
            label: "Hash",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint64_t",
            bytes: [0, 1, 2, 3, 4, 5, 6, 7],
          },
        ],
      },
      "8": {
        Description: "Multi Param Request",
        Fields: [
          {
            label: "ID Req",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint16_t",
            bytes: [0, 1],
          },
          {
            label: "Req",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "Read",
              "255": "Write",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [2],
          },
          {
            label: "Var Type",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "BOOL",
              "1": "BYTE",
              "2": "WORD",
              "3": "DWORD",
              "4": "LWORD",
              "5": "SINT",
              "6": "INT",
              "7": "DINT",
              "8": "LINT",
              "9": "REAL",
              "10": "LREAL",
              "11": "TIME",
            },
            multiplier: 1.0,
            type: null,
            bytes: [3],
          },
          {
            label: "Index1",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [4],
          },
          {
            label: "Index2",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [5],
          },
          {
            label: "Value",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint64_t",
            bytes: [6, 7, 8, 9, 10, 11, 12, 13],
          },
        ],
      },
      "9": {
        Description: "Array Param Request",
        Fields: [
          {
            label: "ID Req",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint16_t",
            bytes: [0, 1],
          },
          {
            label: "Req",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "Read",
              "255": "Write",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [2],
          },
          {
            label: "Var Type",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "BOOL",
              "1": "BYTE",
              "2": "WORD",
              "3": "DWORD",
              "4": "LWORD",
              "5": "SINT",
              "6": "INT",
              "7": "DINT",
              "8": "LINT",
              "9": "REAL",
              "10": "LREAL",
              "11": "TIME",
            },
            multiplier: 1.0,
            type: null,
            bytes: [3],
          },
          {
            label: "Index1 Start",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [4],
          },
          {
            label: "Index1 End",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [5],
          },
          {
            label: "Index2 Start",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [6],
          },
          {
            label: "Index2 End",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [7],
          },
          {
            label: "Value",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint64_t",
            bytes: [8, 9, 10, 11, 12, 13, 14, 15],
          },
        ],
      },
    },
  },
  "Other Messages": {
    Prefixes: {
      "5": {
        prefix_description: "Pin ID",
        Description: "Pin Config",
        Fields: [
          {
            label: "xErrorReset",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "0": "NoReset",
              "255": "Reset",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [0],
          },
          {
            label: "eMode",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [1],
          },
          {
            label: "OutputOffDelay",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "ms",
            multiplier: 100.0,
            type: "uint8_t",
            bytes: [2],
          },
          {
            label: "Response Freq",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "ms",
            multiplier: 50.0,
            type: "uint8_t",
            bytes: [3],
          },
          {
            label: "IgnoreCmdTimeout",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "255": "Ignore",
              "0": "UseTimeout",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [4],
          },
          {
            label: "Reserved",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [5],
          },
          {
            label: "Flags",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 1,
            unit: "",
            bits: [
              {
                Name: "StopOverrideOnEstop",
                Start: 0,
                Num: 1,
              },
              {
                Name: "StopOverrideOnFreeze",
                Start: 1,
                Num: 1,
              },
              {
                Name: "TurnOffOnEstop",
                Start: 2,
                Num: 1,
              },
              {
                Name: "TurnOffOnFreeze",
                Start: 3,
                Num: 1,
              },
              {
                Name: "FlagsConfirmed",
                Start: 4,
                Num: 1,
              },
              {
                Name: "KeepOnInShutdown",
                Start: 5,
                Num: 1,
              },
              {
                Name: "DisableOverride",
                Start: 6,
                Num: 1,
              },
            ],
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [6],
          },
          {
            label: "ControlInStandard",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 1,
            use_bits: 0,
            unit: "",
            enum: {
              "255": "True",
              "0": "False",
            },
            multiplier: 1.0,
            type: "uint8_t",
            bytes: [7],
          },
        ],
      },
      "6": {
        prefix_description: "Pin ID",
        Description: "Output Override Command",
        Fields: [
          {
            label: "Voltage / Current",
            display: 1,
            offset: 0,
            raw: 0,
            sum_bools: 0,
            use_enum: 0,
            use_bits: 0,
            unit: "",
            multiplier: 1.0,
            type: "uint16_t",
            bytes: [0, 1],
          },
        ],
      },
    },
    Messages: {},
  },
};
